let fellowships = [
  "AMES, IA",
  "AUBURN, AL",
  "AUSTIN, TX",
  "BLOOMINGTON, IN",
  "CA Mission Team, CA",
  "CARBONDALE, IL",
  "CEDAR FALLS, IA",
  "CEF",
  "CHAMPAIGN, IL",
  "CHICAGO, IL",
  "COLUMBIA, MO",
  "COLUMBUS, IN",
  "CONWAY, AR",
  "CWC",
  "DALLAS, TX",
  "DENTON, TX",
  "EDMOND, OK",
  "EL PASO (Chinese Baptist), TX",
  "EL PASO, TX",
  "Emmanuel Chinese KANSAS CITY, KS",
  "FAYETTEVILLE, AR",
  "FORT WORTH, TX",
  "FREMONT, CA",
  "FULTON, MO",
  "Greater KANSAS CITY Chinese, KS",
  "GREENWOOD, IN",
  "INDIANAPOLIS, IN",
  "IOWA CITY, IA - Chinese Church of Iowa City",
  "IOWA CITY, IA - Chinese Evangelical Church in Iowa City",
  "IRVING, TX",
  "KIRKSVILLE, MO",
  "LANSING, MI",
  "LAWRENCE, KS",
  "LEWISVILLE, TX",
  "LINCOLN, NE",
  "LITTLE ROCK, AR",
  "LUBBOCK, TX",
  "MADISON, WI",
  "MANHATTAN, KS",
  "MEMPHIS, TN",
  "MICHIGAN",
  "MINNEAPOLIS, MN",
  "NORMAN, OK",
  "North Land KANSAS CITY, MO",
  "NY/NJ",
  "OKC, OK",
  "OLATHE, KS",
  "OMAHA, NE",
  "OTHERS",
  "OXFORD, MS",
  "PEORIA, IL",
  "PITTSBURG, KS",
  "PLANO, TX",
  "ROLLA, MO",
  "SCOTTSBURG, IN",
  "SHAWNEE MISSION, KS",
  "SOUTH BEND, IN",
  "SPEAKERS",
  "SPRINGFIELD, IL",
  "SPRINGFIELD, MO",
  "ST.LOUIS Chinese Baptist, MO",
  "ST.LOUIS Chinese Christian, MO",
  "ST.LOUIS Chinese Gospel, MO",
  "ST.LOUIS Chinese Lutheran, MO",
  "ST.LOUIS Light of Christ LCMS, MO",
  "ST.LOUIS Lighthouse Chinese, MO",
  "ST.LOUIS Taiwanese Presbyterian, MO",
  "STILLWATER, OK",
  "STORRS, CT",
  "TAMPA, FL",
  "TOPEKA, KS",
  "TROY, MI",
  "TULSA, OK",
  "URBANA, IL",
  "VERMILLION, SD",
  "WARRENSBURG, MO",
  "WEST LAFAYETTE, IN",
  "Wichita Bible Study Group, KS",
  "Wichita Emmanuel Chinese Baptist Church, KS",
  "WINTERPARK, FL"
]

export default fellowships;